spring:
  cloud:
    gateway:
      routes:
      - id: microservicio-usuario
        uri: lb://microservicio-usuario
        predicates:
          - Path=/HelpDesk/usuarios/**
        filters:
          - StripPrefix=2
      - id: microservicio-tickets
        uri: lb://microservicio-tickets
        predicates:
          - Path=/HelpDesk/tickets/**
        filters:
          - StripPrefix=2
      - id: microservicio-historial
      - id: microservicio-historial
        uri: lb://microservicio-tickets
        predicates:
          - Path=/HelpDesk/historial/**
        filters:
          - StripPrefix=2
      - id: microservicio-equipo
        uri: lb://microservicio-tickets
        predicates:
          - Path=/HelpDesk/equipos/**
        filters:
          - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
              allowed-origins: 'http://localhost:4200'
              allowed-headers:
                - Content-Type
              allowed-methods:
                - GET
                - POST
                - PUT
                - DELETE